
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WAL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WAL
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'Moya', '~> 14.0'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKAuth'
  pod 'Kingfisher', '~> 7.0'
  pod 'lottie-ios'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  pod 'Firebase/Messaging'

end